### ISSUE TITLE
Feature Request, Subvert: support restriction to visual selection

### ISSUE THREAD

**Issue by bodograumann** [tpope/vim-abolish#56]
To substitute something in a visual selection with standard vim commands one would do:

    :%s/\%Voriginal/replacement/g

It would be nice if Subvert could do something similar. Currently the above syntax only gives a _pattern not found_ error.

**Comment by tpope** [comment]
Is that different from `:'<,'>Subvert`?

**Comment by canaaerus** [comment]
Yes. `:'<,'>` works on whole lines. So when only part of a line is selected or you are in visual block mode, it would do substitutions outside of the selection.

The pattern seems to be converted to

    \v\C%(\\\%VORIGINAL|\\\%Voriginal|\\\%voriginal)

i.e. the backspace and percentage signs are escaped. So it makes sense that this would not match.

Also I just realized that instead of only putting the `\%V` at the beginning, I should probably also put it at the end of the pattern, to ensure that the complete match is inside of the visual selection.

Maybe it would be a good idea to add a new flag `V`which would make `:Subvert/original/replacement/V` surround the pattern with `\%V`.

**Comment by bpj** [comment]
I use [`vis.vim`](https://www.vim.org/scripts/script.php?script_id=1195):

```VimL
:B Subvert/FooBar/BazQuux/
```

Works like a charm, plus works with all commands!

Downside: the `:S` commands of `vis.vim` and Abolish conflict.
I work around that by putting this in my `.vimrc` after both have been loaded:

```VimL
com! -nargs=1 -bang -bar -range=0 S <line1>,<line2>Subvert<bang> <args>
```

**Comment by bodograumann** [comment]
@bpj, that is a good idea. I even have vis.vim installed already.

What I‘m noticing though, is that it inserts spaces around the selected block. Does this happen for you as well?

**Comment by bpj** [comment]
@bodograumann Yes it does, but I think that is a bug in recent versions, so perhaps it should be reported.  

[The vis manual](http://www.drchip.org/astronaut/vim/doc/vis.txt.html) says:

> g:vis_empty_character : this character should not appear in your
> 	text.  By default: users of euc-jp will get a 0x01, otherwise
> 	it wil be a 0xff.  Used to prevent an empty result in the
> 	moving back the modified text operation, which otherwise results
> 	in an unwanted extra blank space being inserted.

I indeed had `g:vis_empty_character` unset, so I set it to both 0xff and to 0x7f, since it isn't entirely ruled out that I will have 0xff in my files, but nothing changes.
I'll send a mail to the author right away.

**Comment by bodograumann** [comment]
Thank you.
I will then close this request. Your solution seems *good enough™*.
